import type { NextApiRequest, NextApiResponse } from 'next';
import PDFDocument from 'pdfkit';
import { format } from 'date-fns';
import { triggerBackgroundCleanup } from '@/lib/pdfCleanup';
import { getReportsDir, ensureDir } from '@/lib/tmpDir';
import fs from 'fs';
import path from 'path';
import { createClient } from '@supabase/supabase-js';

const COLORS = {
  background: '#F7F0E1',
  primary: '#1E1A14',
  accent: '#8A560A',
  secondary: '#4A4133',
  muted: '#6B5F4B',
  border: '#D6C7A8',
  cardBg: '#F2E7CF',
};

/**
 * Helper function to draw a rounded rectangle
 */
function drawRoundedRect(
  doc: PDFKit.PDFDocument,
  x: number,
  y: number,
  width: number,
  height: number,
  radius: number
) {
  doc
    .moveTo(x + radius, y)
    .lineTo(x + width - radius, y)
    .quadraticCurveTo(x + width, y, x + width, y + radius)
    .lineTo(x + width, y + height - radius)
    .quadraticCurveTo(x + width, y + height, x + width - radius, y + height)
    .lineTo(x + radius, y + height)
    .quadraticCurveTo(x, y + height, x, y + height - radius)
    .lineTo(x, y + radius)
    .quadraticCurveTo(x, y, x + radius, y);
}

/**
 * Add header to content pages
 */
function addPageHeader(doc: PDFKit.PDFDocument, title: string, date: string) {
  const headerY = 40;
  
  doc.fontSize(9).fillColor(COLORS.secondary).font('Helvetica');
  doc.text('Executive Report', 50, headerY, { width: 300, ellipsis: true });
  
  const dateText = date;
  const dateWidth = doc.widthOfString(dateText);
  doc.text(dateText, doc.page.width - 50 - dateWidth, headerY);
  
  doc.moveTo(50, headerY + 18)
     .lineTo(doc.page.width - 50, headerY + 18)
     .strokeColor(COLORS.border)
     .lineWidth(1)
     .stroke();
}

/**
 * Add footer to content pages
 */
function addPageFooter(doc: PDFKit.PDFDocument, pageNum: number) {
  const footerY = doc.page.height - 50;
  
  doc.moveTo(50, footerY)
     .lineTo(doc.page.width - 50, footerY)
     .strokeColor(COLORS.border)
     .lineWidth(1)
     .stroke();
  
  doc.fontSize(9).fillColor(COLORS.secondary).font('Helvetica');
  doc.text('Generated by Procurix', 50, footerY + 10);
  
  const pageText = `Page ${pageNum}`;
  const pageWidth = doc.widthOfString(pageText);
  doc.text(pageText, doc.page.width - 50 - pageWidth, footerY + 10);
}

/**
 * Draw gradient-like background
 */
function drawGradientBackground(doc: PDFKit.PDFDocument) {
  doc.rect(0, 0, doc.page.width, doc.page.height).fill(COLORS.background);
}

interface ReportData {
  title: string;
  includeAnalytics: boolean;
  timestamp: string;
  preAnalyzedData?: {
    workCompleted: string[];
    keyDecisions: string[];
    problemsSolved: string[];
    insights: string[];
    actionItems: string[];
    summary?: string;
  };
}

interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
  timestamp: string;
}

// ADD THIS near the bottom of generate.ts, outside the default handler

export async function generateReportFromData(input: {
  title: string;
  includeAnalytics: boolean;
  timestamp: string;
  chatHistory: any[];
  preAnalyzedData?: ReportData['preAnalyzedData'];
}) {
  // Mirror what the handler does:

  triggerBackgroundCleanup();

  const { title, includeAnalytics, preAnalyzedData } = input;

  const chatHistory = input.chatHistory as ChatMessage[];

  const analysis = preAnalyzedData && Object.keys(preAnalyzedData).length > 0
    ? {
        totalMessages: chatHistory.length,
        userMessages: chatHistory.filter(m => m.role === 'user').length,
        assistantMessages: chatHistory.filter(m => m.role === 'assistant').length,
        workCompleted: preAnalyzedData.workCompleted || [],
        keyDecisions: preAnalyzedData.keyDecisions || [],
        problemsSolved: preAnalyzedData.problemsSolved || [],
        insights: preAnalyzedData.insights || [],
        actionItems: preAnalyzedData.actionItems || [],
        topics: [],
        timeRange: {
          start: chatHistory[0]?.timestamp || new Date().toISOString(),
          end: chatHistory[chatHistory.length - 1]?.timestamp || new Date().toISOString(),
        },
      }
    : analyzeChatHistory(chatHistory);

  const pdfBuffer = await generatePDF(title, analysis, includeAnalytics);

  const filename = `executive-report-${format(new Date(), 'yyyy-MM-dd-HHmmss')}.pdf`;
  const tmpDir = getReportsDir();
  ensureDir(tmpDir);
  const filePath = path.join(tmpDir, filename);
  fs.writeFileSync(filePath, pdfBuffer);

  // Use relative path for download URL (works better with Vercel)
  const relativePath = `reports/${filename}`;

  // Attempt persistent storage upload (Supabase). This mitigates /tmp ephemeral loss across lambdas.
  let publicDownloadUrl: string | null = null;
  let storageUploaded = false;
  try {
    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
    const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
    if (supabaseUrl && supabaseKey) {
      const bucket = process.env.SUPABASE_REPORTS_BUCKET || 'reports';
      const supabase = createClient(supabaseUrl, supabaseKey);
      const uploadRes = await supabase.storage
        .from(bucket)
        .upload(filename, pdfBuffer, { contentType: 'application/pdf', upsert: true });
      if (uploadRes.error) {
        console.error('[REPORT STORAGE] Upload error:', uploadRes.error.message);
      } else {
        const { data } = supabase.storage.from(bucket).getPublicUrl(filename);
        publicDownloadUrl = data.publicUrl;
        storageUploaded = true;
        console.log('[REPORT STORAGE] Uploaded to Supabase. Public URL:', publicDownloadUrl);
      }
    } else {
      console.log('[REPORT STORAGE] Supabase env vars missing; skipping persistent upload.');
    }
  } catch (storageErr: any) {
    console.error('[REPORT STORAGE] Unexpected storage error:', storageErr.message);
  }

  return {
    success: true,
    filename,
    downloadUrl: publicDownloadUrl || `/api/download-rfp?path=${encodeURIComponent(relativePath)}`,
    filePath,
    publicDownloadUrl,
    storageUploaded,
    pageCount: analysis.workCompleted.length > 0 ? 3 : 2,
    generatedAt: new Date().toISOString(),
    sections: {
      work: analysis.workCompleted.length,
      decisions: analysis.keyDecisions.length,
      problems: analysis.problemsSolved.length,
      insights: analysis.insights.length,
      actions: analysis.actionItems.length,
    },
  };
}

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  // Enable CORS for internal API calls
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  
  // Handle preflight OPTIONS request
  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }
  
  if (req.method !== 'POST') {
    return res.status(405).json({ message: 'Method not allowed' });
  }

  try {
    console.log('[REPORT API] Request received');
    console.log('[REPORT API] Request headers:', req.headers);
    console.log('[REPORT API] Request method:', req.method);
    
    // Trigger background cleanup of old PDFs (runs async, doesn't block)
    triggerBackgroundCleanup();
    
    const { title, includeAnalytics, timestamp, preAnalyzedData }: ReportData = req.body;
    
    console.log('[REPORT API] Request data:', {
      title,
      includeAnalytics,
      hasPreAnalyzedData: !!preAnalyzedData,
      preAnalyzedDataKeys: preAnalyzedData ? Object.keys(preAnalyzedData) : []
    });

    // Get chat history from request
    const chatHistory = await getChatHistory(req);
    
    console.log('[REPORT API] Chat history:', chatHistory.length, 'messages');

    // Use pre-analyzed data from sub-agent if available, otherwise analyze
    const analysis = preAnalyzedData && Object.keys(preAnalyzedData).length > 0
      ? {
          totalMessages: chatHistory.length,
          userMessages: chatHistory.filter(m => m.role === 'user').length,
          assistantMessages: chatHistory.filter(m => m.role === 'assistant').length,
          workCompleted: preAnalyzedData.workCompleted || [],
          keyDecisions: preAnalyzedData.keyDecisions || [],
          problemsSolved: preAnalyzedData.problemsSolved || [],
          insights: preAnalyzedData.insights || [],
          actionItems: preAnalyzedData.actionItems || [],
          topics: [],
          timeRange: {
            start: chatHistory[0]?.timestamp || new Date().toISOString(),
            end: chatHistory[chatHistory.length - 1]?.timestamp || new Date().toISOString(),
          },
        }
      : analyzeChatHistory(chatHistory);
    
    console.log('[REPORT API] Analysis complete:', {
      workItems: analysis.workCompleted.length,
      decisions: analysis.keyDecisions.length,
      problems: analysis.problemsSolved.length,
      insights: analysis.insights.length,
      actions: analysis.actionItems.length
    });

    // Generate PDF (returns Buffer from PDFKit)
    const pdfBuffer = await generatePDF(title, analysis, includeAnalytics);
    
    console.log('[REPORT API] PDF buffer size:', pdfBuffer.length, 'bytes');

    // Generate filename
    const filename = `executive-report-${format(new Date(), 'yyyy-MM-dd-HHmmss')}.pdf`;

    // Save PDF to cross-platform temporary directory
    const tmpDir = getReportsDir();
    ensureDir(tmpDir);
    
    const filePath = path.join(tmpDir, filename);
    console.log('[REPORT API] Saving PDF to:', filePath);
    
    fs.writeFileSync(filePath, pdfBuffer);
    console.log('[REPORT API] PDF saved successfully');

    // Use relative path for download URL (works better with Vercel)
    const relativePath = `reports/${filename}`;

    // Attempt persistent storage upload
    let publicDownloadUrl: string | null = null;
    let storageUploaded = false;
    try {
      const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
      const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
      if (supabaseUrl && supabaseKey) {
        const bucket = process.env.SUPABASE_REPORTS_BUCKET || 'reports';
        const supabase = createClient(supabaseUrl, supabaseKey);
        const uploadRes = await supabase.storage
          .from(bucket)
          .upload(filename, pdfBuffer, { contentType: 'application/pdf', upsert: true });
        if (uploadRes.error) {
          console.error('[REPORT STORAGE] Upload error:', uploadRes.error.message);
        } else {
          const { data } = supabase.storage.from(bucket).getPublicUrl(filename);
          publicDownloadUrl = data.publicUrl;
          storageUploaded = true;
          console.log('[REPORT STORAGE] Uploaded to Supabase. Public URL:', publicDownloadUrl);
        }
      } else {
        console.log('[REPORT STORAGE] Supabase env vars missing; skipping persistent upload.');
      }
    } catch (storageErr: any) {
      console.error('[REPORT STORAGE] Unexpected storage error:', storageErr.message);
    }

    const response = {
      success: true,
      filename,
      downloadUrl: publicDownloadUrl || `/api/download-rfp?path=${encodeURIComponent(relativePath)}`,
      publicDownloadUrl,
      storageUploaded,
      filePath: filePath, // Absolute path in /tmp for email attachment
      pageCount: analysis.workCompleted.length > 0 ? 3 : 2,
      generatedAt: new Date().toISOString(),
      sections: {
        work: analysis.workCompleted.length,
        decisions: analysis.keyDecisions.length,
        problems: analysis.problemsSolved.length,
        insights: analysis.insights.length,
        actions: analysis.actionItems.length
      }
    };
    
    console.log('[REPORT API] Sending success response:', response);
    
    // Return JSON with download URL and file path
    res.status(200).json(response);
  } catch (error: any) {
    console.error('[REPORT API] Error generating report:', {
      message: error.message,
      stack: error.stack,
      name: error.name
    });
    res.status(500).json({ 
      message: error.message || 'Failed to generate report',
      error: error.toString(),
      stack: process.env.NODE_ENV === 'development' ? error.stack : undefined
    });
  }
}

async function getChatHistory(req: NextApiRequest): Promise<ChatMessage[]> {
  // Get chat history from request body
  const chatHistory: ChatMessage[] = req.body.chatHistory || [];
  
  console.log('[REPORT API] getChatHistory - received:', chatHistory.length, 'messages');
  
  // Ensure proper format
  return chatHistory.map((msg: any) => ({
    role: msg.role === 'user' || msg.role === 'human' ? 'user' : 'assistant',
    content: typeof msg.content === 'string' ? msg.content : JSON.stringify(msg.content),
    timestamp: msg.timestamp || new Date().toISOString()
  }));
}

function analyzeChatHistory(history: ChatMessage[]) {
  const analysis = {
    totalMessages: history.length,
    userMessages: history.filter(m => m.role === 'user').length,
    assistantMessages: history.filter(m => m.role === 'assistant').length,
    workCompleted: [] as string[],
    keyDecisions: [] as string[],
    problemsSolved: [] as string[],
    insights: [] as string[],
    actionItems: [] as string[],
    topics: [] as string[],
    timeRange: {
      start: history[0]?.timestamp || new Date().toISOString(),
      end: history[history.length - 1]?.timestamp || new Date().toISOString(),
    },
  };

  // If no history, return placeholder data
  if (history.length === 0) {
    analysis.workCompleted = ['Report generation requested - no chat history available yet'];
    analysis.keyDecisions = ['User initiated executive report generation'];
    analysis.insights = ['This is the beginning of your conversation'];
    analysis.actionItems = ['Continue using the assistant to populate future reports'];
    return analysis;
  }

  // Analyze content for procurement-specific activities
  const activities = {
    rfps: [] as string[],
    auctions: [] as string[],
    vendors: [] as string[],
    emails: [] as string[],
    reports: [] as string[],
  };

  history.forEach(msg => {
    const content = msg.content;
    const lowerContent = content.toLowerCase();
    
    // Extract RFP activities
    if (lowerContent.includes('rfp') && (lowerContent.includes('generated') || lowerContent.includes('created'))) {
      const rfpMatch = content.match(/RFP[- ](\d+)/i);
      if (rfpMatch) {
        activities.rfps.push(`Generated RFP ${rfpMatch[0]}`);
      }
    }
    
    // Extract auction activities
    if (lowerContent.includes('auction') && (lowerContent.includes('scheduled') || lowerContent.includes('created'))) {
      const aucMatch = content.match(/AUC[- ](\d+)/i);
      if (aucMatch) {
        activities.auctions.push(`Scheduled auction ${aucMatch[0]}`);
      }
    }
    
    // Extract vendor activities
    if (lowerContent.includes('vendor') && (lowerContent.includes('added') || lowerContent.includes('created'))) {
      const vendorMatch = content.match(/added[: ]*([\w\s]+?)(?:\s+to|\s+with|\.|,|$)/i);
      if (vendorMatch) {
        activities.vendors.push(`Added vendor: ${vendorMatch[1].trim()}`);
      }
    }
    
    // Extract email activities
    if (lowerContent.includes('email') && lowerContent.includes('sent')) {
      const emailMatch = content.match(/sent.*?to\s+([\w@.]+)/i);
      if (emailMatch) {
        activities.emails.push(`Email sent to ${emailMatch[1]}`);
      }
    }
  });

  // Populate work completed from activities
  analysis.workCompleted = [
    ...activities.rfps,
    ...activities.auctions,
    ...activities.vendors,
    ...activities.emails,
  ];

  // Analyze content using simple keyword matching for remaining categories
  const keywords = {
    work: ['implemented', 'created', 'built', 'developed', 'completed', 'finished', 'deployed', 'generated', 'added', 'fixed'],
    decisions: ['decided', 'chose', 'selected', 'opted for', 'agreed', 'determined', 'changed', 'updated'],
    problems: ['fixed', 'resolved', 'solved', 'debugged', 'corrected', 'addressed', 'error', 'issue'],
    insights: ['learned', 'discovered', 'realized', 'understood', 'found that', 'noticed', 'important'],
    actions: ['need to', 'should', 'must', 'will', 'plan to', 'next step', 'todo', 'test'],
  };

  // If no specific work found, use keyword extraction
  if (analysis.workCompleted.length === 0) {
    history.forEach(msg => {
      const content = msg.content.toLowerCase();
      
      // Extract work completed
      keywords.work.forEach(kw => {
        if (content.includes(kw)) {
          const sentence = extractSentence(msg.content, kw);
          if (sentence && !analysis.workCompleted.includes(sentence)) {
            analysis.workCompleted.push(sentence);
          }
        }
      });
    });
  }

  history.forEach(msg => {
    const content = msg.content.toLowerCase();
    // Extract decisions
    keywords.decisions.forEach(kw => {
      if (content.includes(kw)) {
        const sentence = extractSentence(msg.content, kw);
        if (sentence && !analysis.keyDecisions.includes(sentence)) {
          analysis.keyDecisions.push(sentence);
        }
      }
    });

    // Extract problems solved
    keywords.problems.forEach(kw => {
      if (content.includes(kw)) {
        const sentence = extractSentence(msg.content, kw);
        if (sentence && !analysis.problemsSolved.includes(sentence)) {
          analysis.problemsSolved.push(sentence);
        }
      }
    });

    // Extract insights
    keywords.insights.forEach(kw => {
      if (content.includes(kw)) {
        const sentence = extractSentence(msg.content, kw);
        if (sentence && !analysis.insights.includes(sentence)) {
          analysis.insights.push(sentence);
        }
      }
    });

    // Extract action items
    keywords.actions.forEach(kw => {
      if (content.includes(kw)) {
        const sentence = extractSentence(msg.content, kw);
        if (sentence && !analysis.actionItems.includes(sentence)) {
          analysis.actionItems.push(sentence);
        }
      }
    });
  });

  // Limit results
  analysis.workCompleted = analysis.workCompleted.slice(0, 10);
  analysis.keyDecisions = analysis.keyDecisions.slice(0, 8);
  analysis.problemsSolved = analysis.problemsSolved.slice(0, 8);
  analysis.insights = analysis.insights.slice(0, 8);
  analysis.actionItems = analysis.actionItems.slice(0, 10);

  return analysis;
}

function extractSentence(text: string, keyword: string): string {
  const sentences = text.split(/[.!?]+/);
  const sentence = sentences.find(s => s.toLowerCase().includes(keyword));
  return sentence ? sentence.trim().substring(0, 150) : '';
}

async function generatePDF(title: string, analysis: any, includeAnalytics: boolean): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      console.log('[REPORT PDF] Starting PDF generation...', {
        title,
        workItems: analysis.workCompleted?.length || 0,
        decisions: analysis.keyDecisions?.length || 0
      });
      
      const doc = new PDFDocument({ 
        size: "A4", 
        margin: 0,
        bufferPages: true
      });
      
      const chunks: Buffer[] = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => {
        console.log('[REPORT PDF] PDF generation completed, size:', Buffer.concat(chunks).length, 'bytes');
        resolve(Buffer.concat(chunks));
      });
      doc.on('error', (err) => {
        console.error('[REPORT PDF] PDFDocument error:', err);
        reject(err);
      });

      const dateStr = format(new Date(), 'MMMM dd, yyyy');
      
      // ==================== PAGE 1: COVER PAGE ====================
      drawGradientBackground(doc);
      
      // Gradient overlay effect
      doc.rect(0, 0, doc.page.width, doc.page.height)
         .fillOpacity(0.1)
         .fill(COLORS.cardBg)
         .fillOpacity(1);
      
      // Logo placeholder - circular badge (larger to fit text properly)
      const logoSize = 120;
      const logoX = doc.page.width / 2;
      const logoY = 200;
      
      doc.circle(logoX, logoY, logoSize / 2)
         .lineWidth(3)
         .strokeColor(COLORS.accent)
         .fillAndStroke(COLORS.background, COLORS.accent);
      
      // Center the text properly within the circle
      const reportText = 'REPORT';
      const textWidth = doc.widthOfString(reportText);
      const textHeight = 20; // approximate font size
      doc.fontSize(20)
         .fillColor(COLORS.secondary)
         .font('Helvetica-Bold')
         .text(reportText, logoX - (textWidth / 2 + 15), logoY - (textHeight / 2  + 2 ));
      
      // Title
      doc.fontSize(32)
         .fillColor(COLORS.primary)
         .font('Helvetica-Bold')
         .text(title, 80, logoY + 100, { 
           width: doc.page.width - 160, 
           align: 'center',
           lineGap: 5
         });
      
      // Subtitle
      doc.fontSize(16)
         .fillColor(COLORS.secondary)
         .font('Helvetica')
         .text('Executive Summary', 80, doc.y + 15, { 
           width: doc.page.width - 160, 
           align: 'center' 
         });
      
      // Date
      doc.fontSize(12)
         .fillColor(COLORS.muted)
         .text(dateStr, 80, doc.page.height - 100, { 
           width: doc.page.width - 160, 
           align: 'center' 
         });
      
      // Summary Stats Cards
      const statsY = 450;
      const cardWidth = (doc.page.width - 160) / 2;
      const cardHeight = 70;
      const cardSpacing = 20;
      
      const stats = [
        { label: 'Total Messages', value: analysis.totalMessages.toString() },
        { label: 'Work Completed', value: analysis.workCompleted.length.toString() },
        { label: 'Key Decisions', value: analysis.keyDecisions.length.toString() },
        { label: 'Action Items', value: analysis.actionItems.length.toString() },
      ];
      
      stats.forEach((stat, idx) => {
        const col = idx % 2;
        const row = Math.floor(idx / 2);
        const cardX = 80 + col * (cardWidth + cardSpacing);
        const cardY = statsY + row * (cardHeight + cardSpacing);
        
        drawRoundedRect(doc, cardX, cardY, cardWidth, cardHeight, 6);
        doc.fillOpacity(0.1).fill(COLORS.accent).fillOpacity(1);
        doc.lineWidth(2).strokeColor(COLORS.accent).stroke();
        
        doc.fontSize(10)
           .fillColor(COLORS.secondary)
           .font('Helvetica-Bold')
           .text(stat.label, cardX + 15, cardY + 15, { 
             width: cardWidth - 30
           });
        
        doc.fontSize(24)
           .fillColor(COLORS.primary)
           .font('Helvetica-Bold')
           .text(stat.value, cardX + 15, cardY + 35, { 
             width: cardWidth - 30
           });
      });

      // ==================== PAGE 2: WORK COMPLETED & DECISIONS ====================
      doc.addPage();
      drawGradientBackground(doc);
      addPageHeader(doc, title, dateStr);
      
      let contentY = 100;
      
      // Work Completed Section
      if (analysis.workCompleted.length > 0) {
        const titleY = contentY;
        doc.fontSize(20)
           .fillColor(COLORS.primary)
           .font('Helvetica-Bold')
           .text('Work Completed', 50, titleY);
        
        // Draw vertical bar aligned with title
        const barHeight = 22;
        doc.moveTo(45, titleY + barHeight)
           .lineTo(45, titleY)
           .lineWidth(4)
           .strokeColor(COLORS.accent)
           .stroke();
        
        contentY = doc.y + 15;
        
        analysis.workCompleted.slice(0, 10).forEach((item: string) => {
          if (contentY > 700) {
            doc.addPage();
            drawGradientBackground(doc);
            addPageHeader(doc, title, dateStr);
            contentY = 100;
          }
          
          // Use proper checkmark bullet
          doc.fontSize(10)
             .fillColor(COLORS.secondary)
             .font('Helvetica-Bold')
             .text('•', 60, contentY);
          
          doc.fontSize(10)
             .fillColor(COLORS.primary)
             .font('Helvetica')
             .text(item, 75, contentY, { 
               width: doc.page.width - 125, 
               lineGap: 5 
             });
          
          contentY = doc.y + 12;
        });
        
        contentY += 15;
      }
      
      // Key Decisions Section
      if (analysis.keyDecisions.length > 0) {
        if (contentY > 650) {
          doc.addPage();
          drawGradientBackground(doc);
          addPageHeader(doc, title, dateStr);
          contentY = 100;
        }
        
        const titleY = contentY;
        doc.fontSize(20)
           .fillColor(COLORS.primary)
           .font('Helvetica-Bold')
           .text('Key Decisions', 50, titleY);
        
        // Draw vertical bar aligned with title
        const barHeight = 22;
        doc.moveTo(45, titleY + barHeight)
           .lineTo(45, titleY)
           .lineWidth(4)
           .strokeColor(COLORS.accent)
           .stroke();
        
        contentY = doc.y + 15;
        
        analysis.keyDecisions.slice(0, 8).forEach((item: string) => {
          if (contentY > 700) {
            doc.addPage();
            drawGradientBackground(doc);
            addPageHeader(doc, title, dateStr);
            contentY = 100;
          }
          
          // Use proper arrow bullet
          doc.fontSize(10)
             .fillColor(COLORS.accent)
             .font('Helvetica-Bold')
             .text('>', 60, contentY);
          
          doc.fontSize(10)
             .fillColor(COLORS.primary)
             .font('Helvetica')
             .text(item, 75, contentY, { 
               width: doc.page.width - 125, 
               lineGap: 5 
             });
          
          contentY = doc.y + 12;
        });
        
        contentY += 15;
      }
      
      addPageFooter(doc, 2);
      
      // ==================== PAGE 3: PROBLEMS & INSIGHTS ====================
      doc.addPage();
      drawGradientBackground(doc);
      addPageHeader(doc, title, dateStr);
      
      contentY = 100;
      
      // Problems Solved Section
      if (analysis.problemsSolved.length > 0) {
        const titleY = contentY;
        doc.fontSize(20)
           .fillColor(COLORS.primary)
           .font('Helvetica-Bold')
           .text('Problems Solved', 50, titleY);
        
        // Draw vertical bar aligned with title
        const barHeight = 22;
        doc.moveTo(45, titleY + barHeight)
           .lineTo(45, titleY)
           .lineWidth(4)
           .strokeColor(COLORS.accent)
           .stroke();
        
        contentY = doc.y + 15;
        
        analysis.problemsSolved.slice(0, 8).forEach((item: string) => {
          if (contentY > 700) {
            doc.addPage();
            drawGradientBackground(doc);
            addPageHeader(doc, title, dateStr);
            contentY = 100;
          }
          
          // Use proper checkmark bullet
          doc.fontSize(10)
             .fillColor(COLORS.secondary)
             .font('Helvetica-Bold')
             .text('•', 60, contentY);
          
          doc.fontSize(10)
             .fillColor(COLORS.primary)
             .font('Helvetica')
             .text(item, 75, contentY, { 
               width: doc.page.width - 125, 
               lineGap: 5 
             });
          
          contentY = doc.y + 12;
        });
        
        contentY += 15;
      }
      
      // Insights Section
      if (analysis.insights.length > 0) {
        if (contentY > 650) {
          doc.addPage();
          drawGradientBackground(doc);
          addPageHeader(doc, title, dateStr);
          contentY = 100;
        }
        
        const titleY = contentY;
        doc.fontSize(20)
           .fillColor(COLORS.primary)
           .font('Helvetica-Bold')
           .text('Key Insights', 50, titleY);
        
        // Draw vertical bar aligned with title
        const barHeight = 22;
        doc.moveTo(45, titleY + barHeight)
           .lineTo(45, titleY)
           .lineWidth(4)
           .strokeColor(COLORS.accent)
           .stroke();
        
        contentY = doc.y + 15;
        
        analysis.insights.slice(0, 8).forEach((item: string) => {
          if (contentY > 700) {
            doc.addPage();
            drawGradientBackground(doc);
            addPageHeader(doc, title, dateStr);
            contentY = 100;
          }
          
          // Use proper star/asterisk bullet for insights
          doc.fontSize(10)
             .fillColor(COLORS.accent)
             .font('Helvetica-Bold')
             .text('*', 60, contentY);
          
          doc.fontSize(10)
             .fillColor(COLORS.primary)
             .font('Helvetica')
             .text(item, 75, contentY, { 
               width: doc.page.width - 125, 
               lineGap: 5 
             });
          
          contentY = doc.y + 12;
        });
      }
      
      addPageFooter(doc, 3);
      
      // ==================== PAGE 4: ACTION ITEMS ====================
      if (analysis.actionItems.length > 0) {
        doc.addPage();
        drawGradientBackground(doc);
        addPageHeader(doc, title, dateStr);
        
        contentY = 100;
        
        const titleY = contentY;
        doc.fontSize(20)
           .fillColor(COLORS.primary)
           .font('Helvetica-Bold')
           .text('Action Items & Next Steps', 50, titleY);
        
        // Draw vertical bar aligned with title
        const barHeight = 22;
        doc.moveTo(45, titleY + barHeight)
           .lineTo(45, titleY)
           .lineWidth(4)
           .strokeColor(COLORS.accent)
           .stroke();
        
        contentY = doc.y + 15;
        
        analysis.actionItems.slice(0, 10).forEach((item: string) => {
          if (contentY > 700) {
            doc.addPage();
            drawGradientBackground(doc);
            addPageHeader(doc, title, dateStr);
            contentY = 100;
          }
          
          // Use proper bullet for action items
          doc.fontSize(10)
             .fillColor(COLORS.accent)
             .font('Helvetica-Bold')
             .text('•', 60, contentY);
          
          doc.fontSize(10)
             .fillColor(COLORS.primary)
             .font('Helvetica')
             .text(item, 75, contentY, { 
               width: doc.page.width - 125, 
               lineGap: 5 
             });
          
          contentY = doc.y + 12;
        });
        
        addPageFooter(doc, 4);
      }

      doc.end();
    } catch (err) {
      console.error('[REPORT PDF] Generation error:', err);
      reject(err);
    }
  });
}
